apiVersion: v1
kind: Pod
metadata:
  name: sailorpod
spec:
  containers:
  - name: sailor
    image: sahithi99/sailor:1.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - name: tomcatport
        containerPort: 8080
        protocol: TCP

